version: '3.0'
services: 
  rasa:
    image: rasa/rasa:2.4.0
    ports: 
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action-server:
    image: rasa/rasa-sdk:2.4.0
    volumes: 
      - ./actions:/app/actions
    ports:
      - 5055:5055